apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://master-node:6443
  name: kubernetes
- cluster:
    certificate-authority: /home/omartini/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Thu, 12 Oct 2023 18:13:36 UTC
        provider: minikube.sigs.k8s.io
        version: v1.31.2
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Thu, 12 Oct 2023 18:13:36 UTC
        provider: minikube.sigs.k8s.io
        version: v1.31.2
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED
- name: minikube
  user:
    client-certificate: /home/omartini/.minikube/profiles/minikube/client.crt
    client-key: /home/omartini/.minikube/profiles/minikube/client.key
