apiVersion: v1
kind: Pod
metadata:
  labels:
    youtube-demo: "True"
  name: kafka-subscriber
  namespace: python-pods
spec:
  nodeSelector:
    kubernetes.io/hostname: "master-node"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: In
            values:
            - 
            - antarctica-west1
  containers:
    - image:  python:3.8-slim
      imagePullPolicy: IfNotPresent
      name:  base
      command: ["/bin/bash", "-c",]
      args: ["while true; do sleep 3; echo hello Pod for kafka-subscriber; done;"]
