apiVersion: v1
kind: Pod
metadata:
  labels:
    youtube-demo: "True"
  name: kafka-subscriber
  namespace: python-pods
spec:
  tolerations:
    - key: node-role.kubernetes.io 
      effect: NoSchedule
      operator: Equal
      value: control-plane    
    - key: app 
      effect: NoSchedule
      operator: Equal
      value: kafka
  containers:
    - image:  python:3.8-slim
      imagePullPolicy: IfNotPresent
      name:  base
      command: ["/bin/bash", "-c",]
      args: ["while true; do sleep 3; echo hello Pod for kafka-subscriber; done;"]
